[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "tkcalendar>=1.6.1",
    "websocket>=0.2.1",
]
